DROP TABLE SPECIALS;
DROP TABLE USERS;
DROP TABLE BUSINESSES;


CREATE TABLE BUSSUSER (
username VARCHAR(10) NOT NULL UNIQUE,
password VARCHAR(15) NOT NULL,
email VARCHAR(100) NOT NULL,
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY
);

CREATE TABLE BUSSPROFILES (
bname VARCHAR(100) NOT NULL,
btype VARCHAR(11) NOT NULL,
description VARCHAR(1000),
phone VARCHAR(50) NOT NULL,
street VARCHAR(50) NOT NULL,
city VARCHAR(100) NOT NULL,
bstate VARCHAR(20) NOT NULL,
zip VARCHAR(9) NOT NULL,
buss_Id INT,
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY;
);

CREATE TABLE USERS (
email VARCHAR(50) NOT NULL,
username VARCHAR(10) NOT NULL UNIQUE,
password VARCHAR(10) NOT NULL,
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY
);

CREATE TABLE USERPROFILES (
fname VARCHAR(50),
lname VARCHAR(50),
phone VARCHAR(12),
picture BLOB(200k),
pictype VARCHAR(30),
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
user_Id INT
);

CREATE TABLE SPECIALS (
sname VARCHAR(50) NOT NULL,
sdate DATE NOT NULL,
stime 
stime2
stype
description VARCHAR(500),
buss_Id INT,
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY
);

ALTER TABLE SPECIALS ADD FOREIGN KEY (buss_Id) REFERENCES BUSINESSES (id) ON DELETE CASCADE;
ALTER TABLE USERPROFILES ADD FOREIGN KEY (user_Id) REFERENCES USERS (id);