DROP TABLE SPECIALS;
DROP TABLE USERS;
DROP TABLE BUSINESSES;


CREATE TABLE BUSINESSES (
bname VARCHAR(100) NOT NULL,
type VARCHAR(11) NOT NULL,
description VARCHAR(1000),
username VARCHAR(10) NOT NULL UNIQUE,
password VARCHAR(15) NOT NULL,
email VARCHAR(100) NOT NULL,
phone VARCHAR(50) NOT NULL,
street VARCHAR(50) NOT NULL,
city VARCHAR(100) NOT NULL,
state VARCHAR(20) NOT NULL,
zip VARCHAR(9) NOT NULL,
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY
);

CREATE TABLE USERS (
fname VARCHAR(50) NOT NULL,
lname VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
username VARCHAR(10) NOT NULL UNIQUE,
password VARCHAR(10) NOT NULL,
phone VARCHAR(12) NOT NULL,
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
buss_Id INT
);


CREATE TABLE SPECIALS (
name VARCHAR(50) NOT NULL,
date DATE NOT NULL,
description VARCHAR(500),
buss_Id INT,
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY
);

ALTER TABLE USERS ADD FOREIGN KEY (buss_Id) REFERENCES BUSINESSES (id);
ALTER TABLE SPECIALS ADD FOREIGN KEY (buss_Id) REFERENCES BUSINESSES (id) ON DELETE CASCADE;
